AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'bin/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/MethodLength:
  CountComments: true
  Max: 20

Lint/ScriptPermission:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

RSpec/BeNil:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

require:
  - rubocop-rake
  - rubocop-rspec
